test with explicit token

diff --git a/.github/workflows/ci_benchmark.yml b/.github/workflows/ci_benchmark.yml
--- a/.github/workflows/ci_benchmark.yml
+++ b/.github/workflows/ci_benchmark.yml
@@ -6,8 +6,8 @@ on:
   pull_request:
     # types: [labeled, synchronize]
 
-permissions:
-  contents: read
+# permissions:
+#   contents: read
 
 jobs:
   ## This code below is to make sure a new commit on a PR with the label
@@ -113,17 +113,48 @@ jobs:
 
           echo "benchmarks done." > benchmarks.log
           # Report and export results for subsequent steps
-          if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
-             exit 1
-          fi
+          # if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
+          #    exit 1
+          # fi
 
       - name: "Check ccache performance"
         shell: bash -l {0}
         run: ccache -s
-        if: always()
+        # if: always()
 
       - uses: actions/upload-artifact@v4
-        if: always()
+        # if: always()
         with:
           name: asv-benchmark-results
           path: benchmarks.log
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: asv-benchmark-results-${{ runner.os }}
+
+      - name: Read artifact
+        id: artifact
+        run: echo "::set-output name=content::$(cat asv-benchmark-results-${{ runner.os }}/benchmarks.log)"
+
+      - name: Create comment
+        uses: actions/github-script@v7
+        if: github.event_name == 'pull_request_target'
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const issue_number = context.payload.pull_request.number;
+            const body = `
+            <details>
+              <summary>Benchmark results</summary>
+              \`\`\`
+              ${{ steps.artifact.outputs.content }}
+              \`\`\`
+            </details>
+            `;
+            github.rest.issues.createComment({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: issue_number,
+              body: body
+            });
