short circuit ci to test comments

diff --git a/.github/workflows/ci_benchmark.yml b/.github/workflows/ci_benchmark.yml
--- a/.github/workflows/ci_benchmark.yml
+++ b/.github/workflows/ci_benchmark.yml
@@ -105,23 +105,23 @@ jobs:
           echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
           echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"
           # Run benchmarks for current commit against base
-          ASV_OPTIONS="--split --show-stderr --factor $ASV_FACTOR --conf asv.ci.conf.json"
-          python -m asv continuous $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
-              | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
-              | tee benchmarks.log
-
-          # Report and export results for subsequent steps
-          if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
-             exit 1
-          fi
+          # ASV_OPTIONS="--split --show-stderr --factor $ASV_FACTOR --conf asv.ci.conf.json"
+          # python -m asv continuous $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
+          #     | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
+          #     | tee benchmarks.log
+          echo "Benchmarking complete." > benchmarks.log
+          # # Report and export results for subsequent steps
+          # if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
+          #    exit 1
+          # fi
 
       - name: "Check ccache performance"
         shell: bash -l {0}
         run: ccache -s
-        if: always()
+        # if: always()
 
       - uses: actions/upload-artifact@v4
-        if: always()
+        # if: always()
         with:
           name: asv-benchmark-results-${{ runner.os }}
           path: benchmarks.log
@@ -131,27 +131,27 @@ jobs:
         with:
           name: asv-benchmark-results-${{ runner.os }}
 
-      - name: Read benchmarks.log
-        id: benchlog
-        uses: juliangruber/read-file-action@v1
-        with:
-          path: asv-benchmark-results-${{ runner.os }}/benchmarks.log
-    
-      - name: Find Comment
-        uses: peter-evans/find-comment@v3
-        id: fc
-        with:
-          issue-number: ${{ github.event.pull_request.number }}
-          comment-author: 'github-actions[bot]'
-          body-includes: Benchmarks log
-  
-      - name: Create or update comment
-        uses: peter-evans/create-or-update-comment@v4
-        with:
-          comment-id: ${{ steps.fc.outputs.comment-id }}
-          issue-number: ${{ github.event.pull_request.number }}
-          body: |
-            Benchmarks log
+      - name: Read artifact
+        id: artifact
+        run: echo "::set-output name=content::$(cat asv-benchmark-results-${{ runner.os }}/benchmarks.log)"
 
-            ${{ steps.benchlog.outputs.content }}
-          edit-mode: replace
+      - name: Create comment
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const issue_number = context.payload.pull_request.number;
+            const body = `
+            <details>
+              <summary>Benchmark results</summary>
+
+              \`\`\`
+              ${{ steps.artifact.outputs.content }}
+              \`\`\`
+            </details>
+            `;
+            github.rest.issues.createComment({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: issue_number,
+              body: body
+            });
